@Presentation_HostAddress = http://localhost:5053

GET {{Presentation_HostAddress}}/api/empresa
Accept: application/json

###

POST {{Presentation_HostAddress}}/api/empresa
Content-Type: application/json
{
    "Nome": "Wjrart",
    "NomeFantasia": "Willian",
    "CpfCnpj": "708.488.361-46" 
}

###
